name: "Terraform Core"

on:
  repository_dispatch:
    types: [account_crawler, ingest, application, host, aws_ecs]

permissions:
  contents: read

jobs:

  # Run the account crawler workflow
  account_crawler:
    if: github.event.action == 'account_crawler'
    name: Account Crawler
    uses: ./.github/workflows/account_crawler.yml
    with:
      newrelic_account_id: ${{ github.event.client_payload.newrelic_account_id }}
      newrelic_api_key: ${{ github.event.client_payload.newrelic_api_key }}
      newrelic_region: ${{ github.event.client_payload.newrelic_region }}
      terraform_destroy: ${{ github.event.client_payload.terraform_destroy }}
    secrets:
      REPO_GITHUB_PAT: ${{ secrets.REPO_GITHUB_PAT }}

  # Run the data ingest workflow
  ingest:
    if: github.event.action == 'ingest'
    name: Data Ingest
    uses: ./.github/workflows/ingest.yml
    with:
      newrelic_account_id: ${{ github.event.client_payload.newrelic_account_id }}
      newrelic_api_key: ${{ github.event.client_payload.newrelic_api_key }}
      newrelic_region: ${{ github.event.client_payload.newrelic_region }}
      terraform_destroy: ${{ github.event.client_payload.terraform_destroy }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      AZURE_BLOB_CONTAINER_NAME: ${{ secrets.AZURE_BLOB_CONTAINER_NAME }}

  # Run the application workflow
  application:
    if: github.event.action == 'application'
    name: Application
    uses: ./.github/workflows/application.yml
    with:
      newrelic_account_id: ${{ github.event.client_payload.newrelic_account_id }}
      newrelic_api_key: ${{ github.event.client_payload.newrelic_api_key }}
      newrelic_region: ${{ github.event.client_payload.newrelic_region }}
      app_relation_map: ${{ github.event.client_payload.app_relation_map }}
      terraform_destroy: ${{ github.event.client_payload.terraform_destroy }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      AZURE_BLOB_CONTAINER_NAME: ${{ secrets.AZURE_BLOB_CONTAINER_NAME }}

  # Run the host workflow
  host:
    if: github.event.action == 'host'
    name: Host
    uses: ./.github/workflows/host.yml
    with:
      newrelic_account_id: ${{ github.event.client_payload.newrelic_account_id }}
      newrelic_api_key: ${{ github.event.client_payload.newrelic_api_key }}
      newrelic_region: ${{ github.event.client_payload.newrelic_region }}
      terraform_destroy: ${{ github.event.client_payload.terraform_destroy }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      AZURE_BLOB_CONTAINER_NAME: ${{ secrets.AZURE_BLOB_CONTAINER_NAME }}

  # Run the AWS ECS workflow
  aws_ecs:
    if: github.event.action == 'aws_ecs'
    name: AWS ECS
    uses: ./.github/workflows/aws_ecs.yml
    with:
      newrelic_account_id: ${{ github.event.client_payload.newrelic_account_id }}
      newrelic_api_key: ${{ github.event.client_payload.newrelic_api_key }}
      newrelic_region: ${{ github.event.client_payload.newrelic_region }}
      terraform_destroy: ${{ github.event.client_payload.terraform_destroy }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      AZURE_BLOB_CONTAINER_NAME: ${{ secrets.AZURE_BLOB_CONTAINER_NAME }}
